'use strict';
const crypto=require('crypto');
const K=new Set(['text','image','video','audio','document','code','3d','web','research']),S=new Set(['active','deleted','all']),D=new Set(['chat','projects','images','video','code','research']);
const E=(code,cause)=>Object.assign(new Error(code),{code,cause});
const text=(v,m=200)=>{if(v===undefined||v===null||v==='')return null;v=String(v).trim();if(!v||v.length>m)throw E('workspace_library_filter_invalid');return v};
const uuid=v=>{v=text(v,80);if(!v)return null;if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v))throw E('workspace_library_filter_invalid');return v};
const date=v=>{v=text(v,80);if(!v)return null;const d=new Date(v);if(!Number.isFinite(d.getTime()))throw E('workspace_library_filter_invalid');return d.toISOString()};
function normalizeLibraryQuery(q={}){const state=text(q.state,20)||'active',kind=text(q.kind,40);if(!S.has(state)||(kind&&!K.has(kind)))throw E('workspace_library_filter_invalid');return{q:text(q.q,300),kind,projectId:uuid(q.projectId),source:text(q.source,80),model:text(q.model,160),from:date(q.from),to:date(q.to),state,limit:Math.max(1,Math.min(Number(q.limit)||50,100)),offset:Math.max(0,Math.min(Number(q.offset)||0,10000))}}
const model=m=>m&&(m.model||m.modelId||m.modelTool)||null,provider=m=>m&&(m.provider||m.providerId)||null;
function allowedDestinations(k){const a=['chat','projects','code'];if(k==='image')return[...a,'images','video'];if(k==='video')return[...a,'video'];if(['research','document','web'].includes(k))return[...a,'research'];return a}
function createWorkspaceLibraryStore(db){
 if(!db||typeof db.from!=='function'||typeof db.rpc!=='function')throw new TypeError('Supabase-compatible db required');
 async function hydrate(owner,rows){if(!rows?.length)return[];const ids=rows.map(x=>x.id),pids=[...new Set(rows.map(x=>x.project_id).filter(Boolean))];
  const ar=await db.from('zuvyr_assets').select('id,canonical_content_id,mime_type,file_size_bytes,status,retention_class,created_at,updated_at,deleted_at').eq('owner_id',owner).in('canonical_content_id',ids).order('created_at',{ascending:false});if(ar.error)throw E('workspace_library_assets_failed',ar.error);
  let ps=[];if(pids.length){const pr=await db.from('workspace_projects').select('id,name').eq('owner_id',owner).in('id',pids);if(pr.error)throw E('workspace_library_projects_failed',pr.error);ps=pr.data||[]}
  const pm=new Map(ps.map(x=>[x.id,x.name])),am=new Map();for(const a of ar.data||[]){const z=am.get(a.canonical_content_id)||[];z.push(a);am.set(a.canonical_content_id,z)}
  return rows.map(x=>{const assets=am.get(x.id)||[];return{id:x.id,kind:x.kind,title:x.title||x.kind,state:x.deleted_at?'deleted':x.status,project_id:x.project_id||null,project_name:pm.get(x.project_id)||null,source_kind:x.source_kind,source_system:x.source_system,source_id:x.source_id,model:model(x.metadata),provider:provider(x.metadata),metadata:x.metadata||{},current_version_id:x.current_version_id||null,asset_count:assets.filter(a=>a.status==='active').length,assets,created_at:x.created_at,updated_at:x.updated_at,deleted_at:x.deleted_at||null}})}
 async function row(owner,id){const r=await db.from('zuvyr_content_objects').select('id,owner_id,project_id,kind,title,status,source_kind,source_system,source_id,metadata,current_version_id,created_at,updated_at,deleted_at').eq('id',id).eq('owner_id',owner).maybeSingle();if(r.error||!r.data)throw E('workspace_library_item_not_found',r.error);return r.data}
 async function listItems({ownerId,filters={}}){const f=normalizeLibraryQuery(filters),r=await db.rpc('search_zuvyr_library',{p_owner_id:ownerId,p_query:f.q,p_kind:f.kind,p_project_id:f.projectId,p_source:f.source,p_model:f.model,p_from:f.from,p_to:f.to,p_state:f.state,p_limit:f.limit,p_offset:f.offset});if(r.error)throw E('workspace_library_search_failed',r.error);return{items:await hydrate(ownerId,r.data||[]),filters:f,has_more:(r.data||[]).length===f.limit}}
 async function getItem({ownerId,contentId}){const x=await row(ownerId,contentId),h=(await hydrate(ownerId,[x]))[0],v=await db.from('zuvyr_content_versions').select('id,version_number,source_version_key,mime_type,uri,sha256,payload,provenance,created_at').eq('owner_id',ownerId).eq('content_id',contentId).order('version_number',{ascending:false}).limit(50);if(v.error)throw E('workspace_library_versions_failed',v.error);return{...h,versions:v.data||[]}}
 async function softDelete({ownerId,contentId}){const i=await getItem({ownerId,contentId});if(i.deleted_at)return i;if(i.assets.some(a=>a.status==='active'&&a.retention_class==='legal_hold'))throw E('workspace_library_legal_hold');const now=new Date().toISOString();let r=await db.from('zuvyr_content_objects').update({status:'archived',deleted_at:now,updated_at:now}).eq('id',contentId).eq('owner_id',ownerId);if(r.error)throw E('workspace_library_delete_failed',r.error);r=await db.from('zuvyr_assets').update({status:'deleted',deleted_at:now,updated_at:now}).eq('owner_id',ownerId).eq('canonical_content_id',contentId).neq('retention_class','legal_hold');if(r.error)throw E('workspace_library_delete_failed',r.error);return getItem({ownerId,contentId})}
 async function restore({ownerId,contentId}){await row(ownerId,contentId);const now=new Date().toISOString();let r=await db.from('zuvyr_content_objects').update({status:'active',deleted_at:null,updated_at:now}).eq('id',contentId).eq('owner_id',ownerId);if(r.error)throw E('workspace_library_restore_failed',r.error);r=await db.from('zuvyr_assets').update({status:'active',deleted_at:null,updated_at:now}).eq('owner_id',ownerId).eq('canonical_content_id',contentId);if(r.error)throw E('workspace_library_restore_failed',r.error);return getItem({ownerId,contentId})}
 async function createDownload({ownerId,contentId,assetId=null}){const i=await getItem({ownerId,contentId});if(i.deleted_at)throw E('workspace_library_item_deleted');let q=db.from('zuvyr_assets').select('id,canonical_content_id,storage_bucket,storage_path,mime_type,file_size_bytes,status').eq('owner_id',ownerId).eq('canonical_content_id',contentId).eq('status','active');if(assetId)q=q.eq('id',assetId);const a=await q.order('created_at',{ascending:false}).limit(1).maybeSingle();if(a.error||!a.data)throw E('workspace_library_asset_not_found',a.error);const s=await db.storage.from(a.data.storage_bucket).createSignedUrl(a.data.storage_path,60,{download:true});if(s.error||!s.data?.signedUrl)throw E('workspace_library_download_sign_failed',s.error);const eg=await db.rpc('record_zuvyr_asset_egress',{p_owner_id:ownerId,p_asset_id:a.data.id,p_request_id:'library:'+crypto.randomUUID(),p_bytes:Number(a.data.file_size_bytes||0),p_purpose:'library_download',p_metadata:{contentId,source:'pack044_library'}});if(eg.error)throw E('workspace_library_egress_record_failed',eg.error);return{asset_id:a.data.id,content_id:contentId,mime_type:a.data.mime_type,file_size_bytes:Number(a.data.file_size_bytes||0),signed_url:s.data.signedUrl,expires_in_seconds:60,upload_required:false,egress:eg.data||null}}
 async function createSendTo({ownerId,contentId,destination}){destination=text(destination,40);if(!destination||!D.has(destination))throw E('workspace_library_destination_invalid');const i=await getItem({ownerId,contentId});if(i.deleted_at)throw E('workspace_library_item_deleted');if(!allowedDestinations(i.kind).includes(destination))throw E('workspace_library_destination_unsupported');return{schema_version:'pack044.library-handoff.v1',destination,canonical_content_id:i.id,canonical_version_id:i.current_version_id,project_id:i.project_id,kind:i.kind,title:i.title,asset_ids:i.assets.filter(a=>a.status==='active').map(a=>a.id),provenance:{source_kind:i.source_kind,source_system:i.source_system,source_id:i.source_id,model:i.model,provider:i.provider},upload_required:false,reuse_mode:'canonical_reference'}}
 return{listItems,getItem,softDelete,restore,createDownload,createSendTo}}
function getDefaultWorkspaceLibraryStore(){return createWorkspaceLibraryStore(require('./supabaseAdmin').supabaseAdmin)}
module.exports={normalizeLibraryQuery,allowedDestinations,createWorkspaceLibraryStore,getDefaultWorkspaceLibraryStore};
